version: '{build}'
skip_tags: true
image: Visual Studio 2017

# Courtesty of https://github.com/starkat99/appveyor-rust/
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build:
  - ps: ./Build.ps1 -version 1.0.

artifacts:
  - path: publish/Seq.App.*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: luVm1C63eoBD+VuUPGu66KsalR39FTAbnQtRgs8HmO21D53xm/I6o0eIN7Tm0Y83
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Seq.App.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
    